### ISSUE TITLE
Strategy "mnt2" always fails

### ISSUE THREAD

**Issue by muffl0n** [utkuozdemir/pv-migrate#114]
**Describe the bug**
Strategy "mnt2" always fails, fallback "svc" works like a charm. Is there a way to get the reason why "mnt2" fails?

**To Reproduce**

1. Create namespace "migrate"
2. Create pvcs "data" and "destination" 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: premium-rwo

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: destination
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: premium-rwo
``` 
3. Run migration
```
-> % pv-migrate migrate data destination
🚀  Starting migration
💭  Will attempt 3 strategies: mnt2,svc,lbsvc
🚁  Attempting strategy: mnt2
🧹  Cleaning up
✨  Cleanup successful
⚠️  Migration failed with this strategy, will try with the remaining strategies
🚁  Attempting strategy: svc
🔑  Generating SSH key pair
🔑  Creating secret for the public key
🚀  Creating sshd pod
⏳  Waiting for the sshd pod to start running
🚀  Sshd pod started
🔑  Creating secret for the private key
🔗  Connecting to the rsync server
📂  Copying data... 100% |████████████████| ()
🧹  Cleaning up
✨  Cleanup successful
✅  Migration succeeded
```

**Expected behavior**
I'd expect the strategy "mnt2" to work. No matter what I do, it always fails and I can't see why.

**Console output**
see above

**Version**
 - Source and destination Kubernetes version: `v1.21.5-gke.1802`
 - Source and destination container runtimes: n/a
 - `pv-migrate version 0.6.3 (commit: 20684eb26a83c54c88ea2f6327d82c43ba7e3389)`
 - `Darwin MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64`
 - Installation method: `homebrew`
 - Source and destination PVC type, size and accessModes: `pd.csi.storage.gke.io`, `ReadWriteOnce`, 10GB
