### ISSUE TITLE
Ability to set LoadBalancer IP and connection IP manually

### ISSUE THREAD

**Issue by MurzNN** [utkuozdemir/pv-migrate#155]
**Is your feature request related to a problem? Please describe.**
My provider gives to nodes only internal IPs, that work with external IP using NAT redirection.

For example, my node has only internal IP like `10.0.0.1` on the network interface, but I can access to it using provided external IP like 213.177.1.2.

So metallb load balancer declares that internal ips to services, but to connect to that service externally we must use other ip like 213.177.1.2.

By that reason `pv-migrate` always fails to make a connection, because it sees only internal IP and try connect to it.

**Describe the solution you'd like**
Solution for this problem can be manually declaring desired LoadBalancer IP to use, and external IP to which connection must be done.

**Comment by MurzNN** [comment]
It can be added to helm values (to be reused using `--helm-set` argument), something like this:
```yaml
sshd:
  service:
   loadBalancerIp: 10.0.0.1
   connectionIp: 213.177.1.2
```

**Comment by utkuozdemir** [comment]
I understand. So you need to be able to specify both `loadBalancerIP` and also the target IP rsync connects to, right?
In that case, your suggestion makes sense:
```yaml
sshd:
  service:
   loadBalancerIP: 10.0.0.1
```

But I'm not sure yet where the connectionIP needs to go. Let me think about this a bit.

**Comment by MurzNN** [comment]
Yes, passing target IP to rsync manually is required step too, because without it they can't find each other.

So better is to move `connectionIP` to rsync section, like this:
```yaml
sshd:
  service:
   loadBalancerIP: 10.0.0.1
rsync:
 connectionIP: 213.177.1.2
```
But we also must somehow mark to which side (source or target) those settings are assigned, and ability to set them to both sides.
