### ISSUE TITLE
Ability to pass annotations to service

### ISSUE THREAD

**Issue by MurzNN** [utkuozdemir/pv-migrate#156]
**Is your feature request related to a problem? Please describe.**
I use `metallb` as load balancer and it has a feature to [share a single IP between several services](https://metallb.universe.tf/usage/#ip-address-sharing) via annotations:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-1.2.3.4"
```

With `metallb` it's common situation that Kubernetes cluster has no free IP addresses pool to assign them to new temporary services, so `pv-migrate` fails in that situation because all IP are busy.

**Describe the solution you'd like**
To solve this problem we can add ability to pass annotations to Service, created by `pv-migrate` via extending Helm chart and adding values like this:
```yaml
sshd:
  service:
    annotations: 
      metallb.universe.tf/allow-shared-ip: "my-key"
```

What do you think about this way of implementing this feature?
