### ISSUE TITLE
More flexible and wide tolerations on migration pod

### ISSUE THREAD

**Issue by bygui86** [utkuozdemir/pv-migrate#76]
**Is your feature request related to a problem? Please describe.**
The tools is amazing but I found some issues running it in a cluster configured with taints on "scheduling" instead of on "running".

**Describe the solution you'd like**
pv-migrate pod can tolerate taints on both "running" and "scheduling".

I suggest to make tolerations a bit more flexible:
```yaml
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists
```

**Describe alternatives you've considered**
I did a little trick on pod startup, adding additional tolerations to it
